### ISSUE TITLE
Simple Hugo Theme Demo on Hugo website contains 3rd party tracking

### ISSUE THREAD

**Issue by onedrawingperday** [Xzya/simple-hugo-theme#1]
Hello @Xzya 

I am one of the maintainers of the [Hugo Themes](https://github.com/gohugoio/hugoThemes/) repository.

Recently I audited the Hugo Themes website and it has [come to my attention](https://github.com/gohugoio/hugoThemes/issues/535) that your theme's demo has third party tracking enabled.

```
     \simple-hugo-theme\exampleSite\config.toml:
        # Google analytics
        googleAnalytics = "UA-47268287-4"
```

To fix this issue please leave the above parameter blank i.e.

```
     \simple-hugo-theme\exampleSite\config.toml:
        # Google analytics
        googleAnalytics = ""
```

Once you look into this please let me know.

Thank you!

**Comment by Xzya** [comment]
Hello @onedrawingperday,

I [commented out](https://github.com/Xzya/simple-hugo-theme/commit/942e373c3795ffd59456abdd4a66b86e8911aa26#diff-991d2a2fe208cdee83955ad6e9a323a7R13) the Google Analytics ID, sorry for that.

Thanks!

**Comment by onedrawingperday** [comment]
Thanks you for the fix @Xzya 👍
